// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smirodxghxhlsyyiggru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaXJvZHhnaHhobHN5eWlnZ3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjY4MTMsImV4cCI6MjA2NDgwMjgxM30.QBrTx8GCeoKyJBc47eMFQAgOiB0tjHkvw91r-v6kVAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);